# -*- coding: utf-8 -*-

"""api请求头"""
headers = [
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv,2.0.1) Gecko/20100101 Firefox/4.0.1",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv,2.0.1) Gecko/20100101 Firefox/4.0.1",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Windows NT 6.1; rv,2.0.1) Gecko/20100101 Firefox/4.0.1",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.8.131 Version/11.11",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Opera/9.80 (Windows NT 6.1; U; en) Presto/2.8.131 Version/11.11",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Maxthon 2.0)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; TencentTraveler 4.0)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; The World)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0; SE 2.X MetaSr 1.0; SE 2.X MetaSr 1.0; .NET CLR 2.0.50727; SE 2.X MetaSr 1.0)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; 360SE)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; Avant Browser)",
    }],
    [{
        "Accept": "*/*",
        "Accept-Encoding": "gzip,deflate",
        "Accept-Language": "zh-Hans-CN, zh-Hans; q=0.5",
        "Cache-Control": "no-cache",
        "Host": "www.aigaogao.com",
        "User-Agent": "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)",
    }],
]

url = "http://www.aigaogao.com/tools/history.html?s="